# -*- coding: utf-8 -*-
"""multiplication_game.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/11wyY3i80bTW3MhpOG49NUPiu6wXh7Y-X
"""

import random
import time

def generate_two_nums():
    return (random.randrange(1, 10), random.randrange(1, 10))

while True:
    num1, num2 = generate_two_nums()
    correct_answer = num1 * num2

    guess = int(input(f"How much is {num1} times {num2}? "))

    while guess != correct_answer:
        print("No. Please try again.")
        guess = int(input(f"How much is {num1} times {num2}? "))

    print("Very good!")

    time.sleep(1)
    desire = input("Do you want to play again (yes / no)? ")
    if desire.upper() == "NO":
        break

print("You have stopped the game.")